### ISSUE TITLE
Can we make these 

### ISSUE THREAD

**Issue by Unlock-ViV** [wilkox/gggenes#25] opened 2020-06-19 07:43 UTC

**Comment by Unlock-ViV** [comment] 2020-06-19 07:48
I just want to know is it possible to get the plot or representation for the genome architecture in a circular format instead of linear?

**Comment by wilkox** [comment] 2020-06-20 01:41
Hey @Unlock-ViV, this is a planned feature but unfortunately not added yet. I'm going to close this issues as it's a duplicate of #7.

**Closed by wilkox** 2020-06-20 01:41 UTC

**Comment by Unlock-ViV** [comment] 2020-06-20 04:57
okay, but can you suggest me how to go about it or this can be achieved?

**Comment by wilkox** [comment] 2020-06-20 08:14
I'm not aware of any R package that can do this currently. You might want to have a look at [Circos](http://circos.ca).

**Comment by Unlock-ViV** [comment] 2020-06-25 13:16
Thank you, I'll try that.
